version: '3.4'

services:
  web:
    environment:
      NODE_ENV: 'production'
    restart: unless-stopped
    command: npm start
    image: zlesyk/hackathon:latest
    container_name: hackathon
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - server
  server:
    image: zlesyk/hackathon:latest
    container_name: hackathon
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: 'production'
    ports:
      - "8082:8082"
    volumes:
      - .:/home/node/app
    command: npm run server