version: '3.4'

services:
  web:
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    image: zlesyk/hackathon:latest
    container_name: hackathon-frontend
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    image: zlesyk/hackathon:latest
    container_name: hackathon-server
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - "8082:8082"
    volumes:
      - .:/home/node/app
    command: npm run server