version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: 'development'
    restart: unless-stopped
    command: npm start
    image: zlesyk/hackathon-client:latest
    container_name: hackathon-client
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: zlesyk/hackathon-server:latest
    container_name: hackathon-server
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: 'development'
    ports:
      - "8082:8082"
    volumes:
      - .:/home/node/app
    command: npm run server